namespace SynthEBD;

// 3-part documentation for the shared NPC-attribute rule editor (UC_NPCAttribute /
// UC_NPCAttributeShell), which every attribute-gated menu embeds: asset-pack subgroup rules,
// whole-config rules, BodyGen/OBody/HeadPart rules, descriptor rules, probability modifiers,
// attribute groups, and the verbose-logging NPC selector.
public static partial class UiDocs
{
    private static void RegisterAttributes()
    {
        Add("Attributes.Summary",
            layperson: "A plain-language readout of this condition: every requirement on the line must hold at once for an NPC to match it. Click the arrow to open the condition for editing.",
            technical: "Generated by VM_NPCAttribute.RefreshSummary, which round-trips the card's shells through their NPCAttribute models and joins each sub-attribute's ToLogString (FormKeys resolved to names/EditorIDs via the link cache) with AND. Refreshes on structural changes, sub-attribute NeedsRefresh signals, and card collapse.",
            motivation: "Distribution rules used to be readable only by mentally decoding nested borders; a live sentence lets you audit a config's logic at a glance without expanding anything.");

        Add("Attributes.ExpandCard",
            layperson: "Shows or hides this condition's editable rows. The one-line summary above stays visible either way.",
            technical: "Toggles VM_NPCAttribute.IsExpanded, which collapses the card body (the GroupedSubAttributes rows). Cards rebuilt from saved settings start collapsed; newly added cards start expanded. Collapsing also refreshes the summary sentence.",
            motivation: "Configs can carry dozens of conditions per rule; collapsing each to a sentence keeps long rule lists scannable while leaving full editing one click away.");

        Add("Attributes.OrSeparator",
            layperson: "An NPC needs to match only ONE of the conditions separated by this line - they are alternatives, not additional requirements.",
            technical: "Conditions in a rule are a HashSet<NPCAttribute> evaluated with OR logic by AttributeMatcher.MatchNPCtoAttributeList; each bordered card below/above this separator is one NPCAttribute.",
            motivation: "Making the OR relationship explicit (instead of implying it by border color) is what lets newcomers read a rule correctly on first sight.");

        Add("Attributes.AndSeparator",
            layperson: "An NPC must match EVERY row joined by this label for the surrounding condition to apply.",
            technical: "Rows within a card are the NPCAttribute.SubAttributes set, evaluated with AND logic - evaluation of the card stops at the first unmatched row.",
            motivation: "AND-within-a-card plus OR-between-cards covers most real distribution rules; labeling both keeps the two directions from being confused.");

        Add("Attributes.AddAndCondition",
            layperson: "Adds another requirement to this condition. The NPC will then have to satisfy the new row IN ADDITION to the existing ones.",
            technical: "Adds a new VM_NPCAttributeShell (defaulting to a Class attribute) to this card's GroupedSubAttributes AND-set.",
            motivation: "Narrowing a condition ('Nord AND female AND not unique') is the most common way rules grow; the labeled button spells out that adding a row narrows rather than broadens.");

        Add("Attributes.AddOrAlternative",
            layperson: "Adds a new, separate condition. NPCs matching EITHER the existing conditions or the new one will satisfy this rule.",
            technical: "Appends a fresh single-shell NPCAttribute card to the host's OR-collection (the same collection this card lives in).",
            motivation: "Broadening a rule ('...or also city guards') is the counterpart to adding AND rows; naming the button after the logic prevents the classic mistake of adding an alternative when a restriction was intended.");

        Add("Attributes.TestCondition",
            layperson: "Opens a tester where you pick any NPC from your load order and immediately see whether it matches this condition, with a per-row breakdown.",
            technical: "Launches Window_AttributeValidator bound to a VM_AttributeValidator for this card, which evaluates the dumped NPCAttribute model against the chosen NPC via AttributeMatcher using the same attribute-group set the owning menu supplies.",
            motivation: "Distribution problems are usually one wrong sub-attribute; testing against a known NPC catches that here rather than after a full patcher run.");

        Add("Attributes.RemoveCondition",
            layperson: "Deletes this whole condition and all of its rows. Other conditions in the rule are unaffected.",
            technical: "Removes this VM_NPCAttribute from its parent OR-collection.",
            motivation: "Card-level removal complements the per-row X, so cleaning up an obsolete alternative doesn't require deleting its rows one by one.");

        Add("Attributes.RemoveRow",
            layperson: "Deletes this single requirement from the condition. If it was the condition's last row, the whole condition is removed.",
            technical: "Removes this shell from the card's GroupedSubAttributes; VM_NPCAttribute.TrimEmptyAttributes then drops the card itself once no shells remain.",
            motivation: "Rules evolve by loosening as often as by tightening; removing one requirement shouldn't disturb the rest of the condition.");

        Add("Attributes.IsIsNot",
            layperson: "Flips this requirement between 'the NPC must match it' (is) and 'the NPC must NOT match it' (is not).",
            technical: "Binds the sub-attribute's Not flag; AttributeMatcher XORs the raw match result with Not before combining rows.",
            motivation: "Negation in leading sentence position ('is not in faction X') reads the way people think about exclusions, unlike the old trailing Not checkbox that was easy to overlook.");

        Add("Attributes.ConditionType",
            layperson: "What kind of NPC property this row checks: their race, class, factions, keywords, voice type, source mod, and so on.",
            technical: "Selects the NPCAttributeType for this shell; switching types swaps in the matching sub-attribute editor, and previously edited values for each type are cached per shell so switching back restores them.",
            motivation: "A dropdown shows the one relevant choice instead of the old permanently-open list of all eleven types, which dominated the editor's footprint.");

        Add("Attributes.ForceMode",
            layperson: "How a match affects distribution: 'Restrict' means only matching NPCs are allowed to receive the item. 'Force If' means matching NPCs strongly prefer this item (without excluding others). 'Force If and Restrict' does both.",
            technical: "Maps to AttributeForcing on the sub-attribute. Restrict/ForceIfAndRestrict rows count toward the rule's restriction check; ForceIf/ForceIfAndRestrict rows add their weight to the ForceIf tally that steers selection toward the carrying item.",
            motivation: "Restriction (gate) and forcing (magnet) are independent axes; exposing the three combinations per row is what lets a single config both limit and steer distribution.");

        Add("Attributes.SubExpressionHeader",
            layperson: "A bracketed sub-condition: the row it belongs to matches when ANY of the conditions inside this box matches. This lets you write logic like 'Nord AND (Companion OR Warrior)' without duplicating rules.",
            technical: "An NPCAttributeSubExpression - an inline anonymous attribute group (nested OR-of-ANDs) evaluated recursively by AttributeMatcher with the row's forcing mode forwarded to the nested conditions, exactly like a named Group reference. Configs that use sub-expressions require a SynthEBD version that knows the SubExpression attribute type; older versions ignore the row with a warning.",
            motivation: "Without parenthetical nesting, 'x AND (y OR z)' had to be distributed into '(x AND y) OR (x AND z)' or factored into a named attribute group - both painful to maintain for one-off logic.");

        Add("Attributes.SubExpressionAddCondition",
            layperson: "Adds the first condition to this empty sub-condition box.",
            technical: "Creates a new single-row condition card in the sub-expression's nested OR-collection. Once one card exists, further alternatives are added with the card's own '+ OR alternative' button.",
            motivation: "Empty sub-expressions never match anything, so the empty state needs exactly one affordance: start the first condition.");

        Add("Attributes.ForceIfWeight",
            layperson: "How strongly a match pulls this item toward the NPC, relative to other Force If matches. Higher numbers win.",
            technical: "The sub-attribute's Weighting, summed into matchedForceIfAttributeWeightedCount when the row (and its whole card) matches; candidates with the highest tally are preferred during selection.",
            motivation: "When multiple forced options match the same NPC, weights decide which one dominates instead of leaving it to random chance.");
    }
}
