namespace SynthEBD;

// 3-part documentation for the Asset Patching (Textures and Meshes) menu, the Config Editor page
// chrome, and the Destandalone Patching page.
public static partial class UiDocs
{
    private static void RegisterAssetPatching()
    {
        // ===== Asset Patching (Textures and Meshes) menu =====

        Add("AssetPatching.ChangeNPCTextures",
            layperson: "Allows installed config files to change NPC textures - the image files that give skin its color and detail. Uncheck it to keep every NPC's original textures while still allowing other kinds of changes.",
            technical: "Mirrors TexMeshSettings.bChangeNPCTextures. Acts as a permission gate during record generation: any assigned asset path ending in .dds is skipped when this is off, so texture sets are never redirected.",
            motivation: "Lets you keep a curated texture setup while still using configs for meshes, or quickly rule textures in or out when diagnosing a visual problem.");

        Add("AssetPatching.ChangeNPCMeshes",
            layperson: "Allows installed config files to change NPC meshes - the 3D model files that define body and head shapes. Uncheck it to keep every NPC's original models.",
            technical: "Mirrors TexMeshSettings.bChangeNPCMeshes. The mesh counterpart of the texture gate: assigned asset paths ending in .nif are skipped during record generation when this is off.",
            motivation: "Useful when configs should distribute only textures - for example when your own body meshes must stay untouched, or a config's bundled meshes conflict with your setup.");

        Add("AssetPatching.ChangeNPCHeadParts",
            layperson: "Allows config files to add or change head features, such as scars or extra face details, that they bring along with their textures. Uncheck it to stop configs from touching those.",
            technical: "Mirrors TexMeshSettings.bChangeNPCHeadParts: permission for asset configs to create or edit HeadPart records via their record templates. Head parts generated by configs are only delivered when Head Part randomization is also enabled in General Settings; otherwise the patcher suppresses them and logs a warning naming the config.",
            motivation: "Some configs ship head-part edits alongside their textures; this switch lets cautious users accept a config's textures and meshes without letting it alter faces.");

        Add("AssetPatching.FacePatchingMode",
            layperson: "Chooses how new face textures reach NPCs in-game. 'Script' applies them while you play using a small script; 'NifEdit' bakes them directly into each NPC's face model file so no script is needed.",
            technical: "Mirrors TexMeshSettings.FacePatchingMode (Script vs NifEdit). Script mode writes JSON dictionaries consumed by the EBD Papyrus scripts at runtime and leaves FaceGen NIFs untouched; NifEdit mode bakes the assigned textures into each FaceGen NIF's shader texture set, making the NIF itself the delivery mechanism. This is one axis of the 16-case patch-mode truth table documented in Patcher.RunPatcher.",
            motivation: "Script mode is the original EBD behavior and updates faces dynamically, but depends on the script runtime; NifEdit produces a script-free result for setups where Papyrus overhead or script-mod dependencies are a concern.");

        Add("AssetPatching.SkyPatcherMode",
            layperson: "Applies skin changes through the SkyPatcher mod instead of editing NPC records in SynthEBD's plugin. NPCs keep their original plugin records and SkyPatcher redirects their appearance while you play. Requires SkyPatcher to be installed.",
            technical: "Mirrors TexMeshSettings.bSkyPatcherModeAssets. Instead of overriding the original NPC record, the patcher creates a surrogate NPC in the output plugin carrying the assigned WornArmor and appearance, then emits SkyPatcher ini directives (skin=, plus copyVisualStyle= when face NIFs are baked) that transfer the surrogate's look to the original NPC at runtime. Incompatible with the original (legacy) EBD face script.",
            motivation: "Exists chiefly to dodge the 'Too Many Masters' plugin limit and record conflicts: because no NPC overrides are written, SynthEBD.esp needs far fewer masters and cannot lose conflicts with other NPC-editing mods.");

        Add("AssetPatching.PatchNPCsWithCustomBodies",
            layperson: "Also patch NPCs that already come with their own custom body textures, usually from follower or NPC-overhaul mods. Turn this off to leave those NPCs exactly as their mod author made them.",
            technical: "Mirrors TexMeshSettings.bApplyToNPCsWithCustomSkins. When off, AssetSelector blocks asset assignment for NPCs whose WornArmor (WNAM) record comes from a non-base-game plugin; skins recognized as EasyNPC vanilla forwards are still treated as vanilla.",
            motivation: "Mod-added NPCs often ship hand-matched body textures, and patching over them can produce mismatched skins. This toggle picks between maximum coverage and maximum safety.");

        Add("AssetPatching.PatchNPCsWithCustomFaces",
            layperson: "Also patch NPCs that already have custom face textures from another mod. Turn this off to skip them so their carefully made faces are not altered.",
            technical: "Mirrors TexMeshSettings.bApplyToNPCsWithCustomFaces. When off, AssetSelector skips asset assignment for NPCs whose HeadTexture record comes from a non-base-game plugin.",
            motivation: "Replacing face textures on NPCs whose FaceGen was built around a specific texture risks the dark-face bug or a mismatched look; skipping them preserves overhauled NPCs.");

        Add("AssetPatching.EnableAssetReplacers",
            layperson: "Lets config files swap out specific existing details on an NPC, such as replacing a particular vanilla scar texture with a new version that matches the assigned skin. Turn it off to allow only whole-look assignments.",
            technical: "Mirrors TexMeshSettings.bEnableAssetReplacers. After primary and mix-in assignment, AssetReplacerSelector evaluates each config's replacer groups: a group applies only if the NPC actually has the targeted record or path (a specific head part, a hardcoded head-part texture, or a generic record path), and valid groups are assigned as additional subgroup combinations.",
            motivation: "Replacers keep existing details like scars consistent with a newly assigned skin - without them an NPC could receive a new complexion while keeping a vanilla-resolution scar that no longer matches.");

        Add("AssetPatching.ReplaceSkins",
            layperson: "A list of skin names that should be removed outright instead of edited. If an NPC has one of these assigned as its skin, SynthEBD clears it so the NPC falls back to its normal racial skin, which SynthEBD then patches cleanly.",
            technical: "Mirrors TexMeshSettings.StrippedSkinWNAMs (armor EditorIDs; defaults SkinNaked and SkinNakedBeast). At record-generation setup the load order's armors are scanned for these EditorIDs; an NPC whose WornArmor matches gets that WNAM cleared on its override before asset records are built. In EasyNPC compatibility mode, 'Patched'-suffixed variants of each EditorID are matched too.",
            motivation: "Tools like EasyNPC assign explicit default-skin WNAM records that would make NPCs look custom-skinned and interfere with patching; stripping them lets SynthEBD treat those NPCs normally.");

        Add("AssetPatching.ImportSkinsFromMod",
            layperson: "Adds every body-slot armor from the selected plugin to the Replace Skins list in one click. Use Undo to revert the last import. Do not import your EasyNPC plugin here - use the EasyNPC Compatibility Mode checkbox instead.",
            technical: "Iterates the selected mod's Armor records whose BodyTemplate first-person flags include Body and appends their EditorIDs to StrippedSkinWNAMs (records without an EditorID are skipped). Each import snapshots the list so Undo can restore it.",
            motivation: "Skin-overhaul plugins can define many skin armors; importing them wholesale is much faster than typing EditorIDs one at a time.");

        Add("AssetPatching.EasyNPCCompatibilityMode",
            layperson: "Makes SynthEBD work smoothly with NPCs processed by EasyNPC by ignoring the placeholder skins EasyNPC assigns. Leave this on if you use EasyNPC.",
            technical: "Mirrors TexMeshSettings.bEasyNPCCompatibilityMode. Two effects: skins whose EditorIDs are in the known EasyNPC vanilla-skin set are treated as vanilla when deciding whether an NPC has a custom skin, and 'Patched'-suffixed variants of each Replace Skins EditorID are also matched for stripping.",
            motivation: "EasyNPC forwards explicit SkinNaked-style WNAM records onto NPCs; without this mode those NPCs would be misread as having custom skins and be skipped or mishandled.");

        Add("AssetPatching.FixEBDGlobalScript",
            layperson: "Includes repaired versions of the EBD helper scripts in SynthEBD's output instead of relying on the original, buggier ones. Recommended to leave on.",
            technical: "Mirrors TexMeshSettings.bApplyFixedScripts: ships SynthEBD's fixed builds of the EBD framework's global Papyrus scripts alongside the output. Sub-options pick the variant - by SKSE version on Skyrim SE, or powerofthree-based on Skyrim VR.",
            motivation: "The original EBD global script has known bugs (notably failing when an NPC head's Full Name does not match its EditorID); shipping fixed scripts corrects runtime behavior without requiring a separately patched EBD install.");

        Add("AssetPatching.FixedScriptSKSEVersion",
            layperson: "Chooses which repaired script version to install based on your game's SKSE version. Pick the one matching your Skyrim SE version; the newer one is recommended if it applies.",
            technical: "Selects between the fixed EBD global script builds targeting SKSE for game versions below 1.5.97 versus 1.5.97 and higher (persisted as TexMeshSettings.bFixedScriptsOldSKSEversion). The 1.5.97+ variant is recommended because it does not bug out when an NPC head's Full Name does not match its EditorID. Shown only for Skyrim SE environments.",
            motivation: "The script fix relies on version-specific SKSE functionality, so the right build must match the game runtime you actually play on.");

        Add("AssetPatching.FixedScriptPO3Mode",
            layperson: "On Skyrim VR, uses versions of the repaired scripts built on powerofthree's mods, which behave more reliably. Requires those mods and their VR adaptations to be installed.",
            technical: "Mirrors TexMeshSettings.bPO3ModeForVR, shown only for Skyrim VR environments. Selects the fixed EBD global script variant built on powerofthree's Papyrus Extender and Tweaks; the Extender, Tweaks, and both of their VR adaptations must all be installed.",
            motivation: "VR lacks the newer SKSE functionality the SE fix uses; powerofthree's extensions provide an equivalent path so VR users also avoid the Full Name versus EditorID script bug.");

        Add("AssetPatching.UseOriginalEBDScript",
            layperson: "Uses the original EBD mod's face script instead of SynthEBD's updated one. Only turn this on if you specifically need the old behavior.",
            technical: "Mirrors TexMeshSettings.bLegacyEBDMode. In Script face-patching mode, legacy mode tags patched NPCs with the original EBD face/script keywords consumed by EBD's own face-texture script rather than the SynthEBD keyword consumed by the updated script; the refresh-trigger and verbose options only apply to the updated script. Mutually exclusive with SkyPatcher asset mode - the UI prompts and reverts one of the two. The EBD Global fix is still applied independently if enabled.",
            motivation: "A fallback for users whose setups depend on the original EBD runtime; the updated SynthEBD script is otherwise recommended and required by some features.");

        Add("AssetPatching.FaceScriptVerbose",
            layperson: "Makes the face script show corner notifications and write detailed entries to the game's script log whenever it changes a face. Meant for testing, not normal play.",
            technical: "Mirrors TexMeshSettings.bNewEBDModeVerbose and applies only to SynthEBD's updated face-texture script (not legacy mode): the runtime shows top-left notifications and logs each application event to the Papyrus log.",
            motivation: "When face textures do not appear in-game, this shows whether the script is running and what it did, at the cost of notification spam - hence testing only.");

        Add("AssetPatching.AssignmentLog",
            layperson: "Writes a report file after patching that lists exactly which looks each NPC received. Useful for checking results without opening the game.",
            technical: "Mirrors TexMeshSettings.bGenerateAssignmentLog. When enabled, the run writes a combination-assignment log to the output folder documenting, per NPC, the chosen subgroup combination and the records generated for it.",
            motivation: "An audit trail: when an NPC looks wrong in-game, the log traces the appearance back to the exact config and subgroups so you can adjust the right rules.");

        Add("AssetPatching.CacheRecords",
            layperson: "Reuses previously generated data for NPCs that get identical looks, making patching noticeably faster. In very rare cases it could assign a wrong record - turn it off if results look mixed up.",
            technical: "Mirrors TexMeshSettings.bCacheRecords. RecordGenerator caches generated sub-record objects keyed by asset-path signature and record template, so NPCs receiving the same combination reuse records instead of regenerating them; rare edge cases in signature matching can mis-share a record.",
            motivation: "Large load orders repeat the same combinations across thousands of NPCs; caching cuts patching time substantially, and the toggle exists as an escape hatch for the rare mismatch.");

        Add("AssetPatching.MatchSkinAltTextures",
            layperson: "If an NPC's skin lists alternate textures that point at a texture SynthEBD just replaced, update those entries too so everything stays in sync.",
            technical: "Mirrors TexMeshSettings.bPatchSkinAltTextures. After converting a combination to records, the skin patcher walks the NPC's skin armor addons' alternate-texture lists and remaps entries referencing texture sets SynthEBD replaced to the newly generated ones.",
            motivation: "Alternate-texture entries would otherwise keep pointing at the old texture set, producing body parts that visibly do not match the newly assigned skin.");

        Add("AssetPatching.MatchArmorTextures",
            layperson: "If an NPC's clothing or armor reuses its body texture, patch the armor too so skin visible through or around the outfit matches the new look.",
            technical: "Mirrors TexMeshSettings.bPatchArmors. After record conversion, the armor patcher updates worn armor records whose texture sets reference the NPC's replaced body textures so the clothed appearance uses the newly assigned textures.",
            motivation: "Some outfits bake the body texture into their own records; without this, an NPC would show the new skin when naked and the old skin in clothes - most visible at neck and wrist seams.");

        Add("AssetPatching.PathTrimming",
            layperson: "Rules that strip standard folder prefixes from asset file paths before they are written, so the game finds the files where it expects them. Most users never need to touch this.",
            technical: "Mirrors TexMeshSettings.TrimPaths: per-extension prefix-trim rules applied when config asset paths are normalized into record and script paths. Defaults remove a leading 'textures' folder from .dds paths and 'meshes' from .nif and .tri paths, because the game stores those paths relative to the respective Data subfolder.",
            motivation: "Config authors reference files by their Data-relative location, but plugin records expect textures/meshes-relative paths; the trim rules bridge the two conventions and are editable for unusual layouts.");

        Add("AssetPatching.RestoreDefaultTrimPaths",
            layperson: "Puts the path trimming list back to its standard entries in case it was changed or broken.",
            technical: "Replaces the current TrimPaths collection with the Settings_TexMesh defaults: trim 'textures' from .dds paths and 'meshes' from .nif and .tri paths.",
            motivation: "Wrong trim rules silently produce records pointing at nonexistent files; a one-click reset beats reconstructing the defaults by hand.");

        Add("AssetPatching.SelectConfigsAll",
            layperson: "Turns on every installed config file for the next patcher run.",
            technical: "Sets IsSelected on every loaded asset pack view model; the selected set persists as TexMeshSettings.SelectedAssetPacks and only selected packs participate in distribution.",
            motivation: "Convenience for large config collections - re-enable everything without clicking each entry.");

        Add("AssetPatching.SelectConfigsNone",
            layperson: "Turns off every installed config file so none of them are used in the next patcher run.",
            technical: "Clears IsSelected on every loaded asset pack view model; deselected packs are excluded from flattening and distribution but remain installed.",
            motivation: "Handy starting point when you want to run with just one or two configs out of many.");

        Add("AssetPatching.DistributionOrder",
            layperson: "The order in which config files get to assign their looks to each NPC - drag and drop to rearrange. Configs earlier in the list get first pick.",
            technical: "Mirrors TexMeshSettings.AssetOrder: an ordered list containing the Primary slot plus each Mix-In config name. The per-NPC assignment loop walks this order, so the Primary slot assigns the main combination (and body shape) at its position and each Mix-In rolls at its own; Specific NPC Assignments can carry their own overriding order.",
            motivation: "When several configs can touch the same NPC - a primary skin config plus mix-in overlays - order determines precedence and how later assignments interact with earlier ones.");

        Add("AssetPatching.InstallConfigArchive",
            layperson: "Installs a downloaded config file from its installer archive, including any textures and meshes bundled with it. This is the recommended way to add configs.",
            technical: "Runs the ConfigInstaller on a SynthEBD installer archive (7z/zip with a Manifest.json): prompts through the manifest's options, extracts the config json plus its assets to the right locations, applies version-compatibility updates, and auto-selects the new packs.",
            motivation: "Archives keep a config and its assets together with install-time choices, eliminating the manual file placement that loose-json installs require.");

        Add("AssetPatching.InstallConfigJson",
            layperson: "Installs a config from a loose .json file without any bundled textures or meshes. Only use this if you know the required files are already installed - the archive installer is preferred.",
            technical: "Loads a single asset-pack json via SettingsIO_AssetPack, re-homes its file path into the asset-pack settings folder, applies version-compatibility updates, and selects it. No assets are copied and no manifest options run, so referenced files must already exist in your load order.",
            motivation: "An escape hatch for configs distributed as bare json (or your own files from elsewhere); it skips the packaging safety net, hence not recommended.");

        Add("AssetPatching.ValidateConfigs",
            layperson: "Checks all enabled config files for problems, such as missing texture files or broken rules, and reports what it finds.",
            technical: "Runs each selected asset pack's Validate() against the current BodyGen and OBody settings (view models are dumped to models first so the check sees unsaved edits). Errors are aggregated per config and written to the log display; a popup confirms when everything passes.",
            motivation: "Catches broken references before a long patch run does - a missing asset or dangling rule found here saves a failed or visually wrong patch later.");

        Add("AssetPatching.SimulateDistribution",
            layperson: "Opens a tool that pretends to patch a chosen NPC many times and shows statistics on which looks they would get and how often. Nothing is written to disk.",
            technical: "Opens the asset distribution simulator window (VM_AssetDistributionSimulator): it runs the real selection logic repeatedly for a chosen NPC against the currently enabled configs and tallies which packs and subgroups are assigned, without generating any output records or files.",
            motivation: "Distribution rules interact in non-obvious ways; simulating one NPC verifies your probability weights and allow/disallow rules actually produce the intended odds before you commit to a full run.");

        // ===== Config Editor page chrome =====

        Add("ConfigEditor.CreateNewConfig",
            layperson: "Starts a brand new, empty config file that you can build up in the editor below.",
            technical: "Creates a fresh AssetPack model containing one starter subgroup (ID 'FS', 'First Subgroup'), adds it to the installed packs, and displays it in the primary editor pane.",
            motivation: "The entry point for authoring your own distribution config instead of installing someone else's.");

        Add("ConfigEditor.PackageConfigs",
            layperson: "Bundles your config file(s) together with their textures and meshes into a single installer archive you can share with others.",
            technical: "Opens the config packager window (backed by a manifest view model) where you compose a Manifest.json - install options, destination paths, and included configs - and emit the archive that 'Install Config from Archive' consumes on the receiving end.",
            motivation: "Distribution-ready packaging is what makes configs portable: recipients get the config, its assets, and guided install choices in one file.");

        Add("ConfigEditor.ValidateConfigs",
            layperson: "Checks all enabled config files for problems, such as missing texture files or broken rules, and reports what it finds.",
            technical: "Same command as the Asset Patching menu's validator: runs each selected asset pack's Validate() against current BodyGen and OBody settings and logs aggregated per-config errors, or confirms success with a popup.",
            motivation: "Authoring naturally introduces broken paths and dangling references; validating from inside the editor catches them the moment they are made.");

        Add("ConfigEditor.SplitScreen",
            layperson: "Shows two config files side by side so you can drag subgroups from one into the other.",
            technical: "Toggles the secondary asset-presenter pane (bShowSecondaryAssetPack). Both panes are full editors over the shared Textures and Meshes view model, and subgroups support drag-and-drop transfer between the displayed configs.",
            motivation: "Merging configs or reorganizing content across files is far easier with both trees visible than by round-tripping through a single pane.");

        Add("ConfigEditor.BatchActions",
            layperson: "Applies one editing action to many config files at once instead of opening each file and repeating the change.",
            technical: "Opens the batch-actions dialog (VM_TexMeshBatchActions): you author a single NPC attribute and apply it as an Allowed or Disallowed distribution rule across all or selected asset packs in one operation.",
            motivation: "Rules that should span your whole collection - like excluding a follower mod's NPCs everywhere - would otherwise require identical hand edits in every config.");

        Add("ConfigEditor.SubgroupPreview",
            layperson: "Chooses how the selected subgroup's contents are previewed: not at all, as flat texture thumbnails, or as a 3D character wearing those textures.",
            technical: "Mirrors TexMeshSettings.PreviewMode (None / Image / Render). Image mode decodes the subgroup's DDS textures to thumbnails; Render mode feeds them to the embedded CharacterViewer OpenGL renderer, which displays a live 3D NPC with the subgroup's textures applied.",
            motivation: "Judging skin textures from file names is guesswork; thumbnails are quick, and the 3D render shows how a texture actually reads on a body, at some memory and GPU cost.");

        Add("ConfigEditor.MaxPreviewImageSize",
            layperson: "The largest size, in pixels, at which preview images are shown. Lower it if previews are using too much memory.",
            technical: "Mirrors TexMeshSettings.MaxPreviewImageSize: the maximum edge length for displayed preview images; larger source textures are downscaled to this bound before display.",
            motivation: "Modern 4K/8K skin textures decoded at full size can consume gigabytes across a config; capping the preview size keeps the editor responsive.");

        // ===== Destandalone Patching page =====

        Add("Destandalone.ForceVanillaBodyPaths",
            layperson: "Makes every patched NPC use your normal installed body models (the standard file locations) instead of the special standalone bodies bundled inside config files. Turn this on if you build your own bodies with BodySlide and want them on everyone.",
            technical: "Mirrors TexMeshSettings.bForceVanillaBodyMeshPath. After asset assignment, VanillaBodyPathSetter walks all patchable NPCs and rewrites worn-armor armature (ARMA) world-model paths that are non-vanilla and not config-assigned back to the race-default body/hands/feet/tail paths, resolved from each race's Skin armor with an ArmorRace (RNAM) fallback. Changes apply via armature edits or cloned surrogate armors and WornArmor overrides, or via SkyPatcher ApplySkin directives when SkyPatcher asset mode is on. NPCs and plugins can be exempted with the block list's Vanilla Body Path flag.",
            motivation: "Config files ship pre-built standalone bodies so they work on any setup, but if you generate your own BodySlide output you want YOUR body on every NPC - this 'de-standalones' the patch, which is the page's namesake.");

        Add("Destandalone.AllowUBE",
            layperson: "Keeps UBE bodies working when forcing standard body paths. UBE is a different body system with its own model files, and forcing those NPCs onto the standard body would break them.",
            technical: "Mirrors TexMeshSettings.bAllowUBEBodyPaths. Armatures whose world-model path contains the '!UBE' marker are preserved in place when their sibling morph .tri file exists (checked loose and in BSAs); when the .tri is missing, the path is remapped to the canonical UBE base body for its slot under the '!UBE' folder instead of the CBBE/UNP vanilla path. Non-UBE armatures fall through to the normal race-default logic.",
            motivation: "UBE meshes are incompatible with standard body paths, so blanket forcing would clobber intentionally UBE NPCs; recognizing them lets destandalone patching coexist with a mixed UBE setup.");
    }
}
