namespace SynthEBD;

/// <summary>
/// Contains the permutation and asssociated data generated by one iteration of the GenerateCombination() function
/// By tracking previously-generated combinations, the patcher avoids entering an infinite loop of re-generating combinations trying to find one that satisfied subgroup and bodygen constraints
/// </summary>
public class AssignmentIteration
{
    /// <summary>Initializes an empty iteration with no previously-generated combinations recorded.</summary>
    public AssignmentIteration()
    {
        PreviouslyGeneratedCombinations = new HashSet<string>();
    }
    /// <summary>Seed subgroups still eligible to begin a combination; depleted as seeds are tried and rejected.</summary>
    public List<FlattenedSubgroup> AvailableSeeds { get; set; } = new();
    /// <summary>The seed subgroup chosen for the current combination attempt.</summary>
    public FlattenedSubgroup ChosenSeed { get; set; } = null;
    /// <summary>The asset pack the current combination is being built from (set by <see cref="ChooseSeedSubgroup"/>).</summary>
    public FlattenedAssetPack ChosenAssetPack { get; set; } = null;
    /// <summary>Snapshot of the working asset pack taken as each subgroup position is filled, enabling <see cref="BackTrack"/> to revert to an earlier position's state when a constraint fails.</summary>
    public Dictionary<int, FlattenedAssetPack> BacktrackSnapshotsByPosition { get; set; } = new();
    /// <summary>Signatures of combinations already produced this pass, used to avoid re-generating the same combination in an infinite loop.</summary>
    public HashSet<string> PreviouslyGeneratedCombinations = new HashSet<string>();

    /// <summary>
    /// Picks a parent asset pack (weighted by its distribution probability) from the supplied seeds, then a
    /// seed subgroup within that pack (weighted by the seed's probability). Sets <see cref="ChosenAssetPack"/>
    /// and <see cref="ChosenSeed"/>; both remain null if no asset pack could be selected.
    /// </summary>
    /// <param name="availableSeeds">Candidate seed subgroups across all available asset packs.</param>
    /// <param name="packWeightSelector">Weight of a candidate asset pack for the current NPC (DistributionRules
    /// ProbabilityWeighting times any matching config-level ProbabilityWeightModifier factors), so a config-level modifier
    /// is honored when choosing the seed pack.</param>
    /// <param name="seedWeightSelector">Weight of a seed subgroup for the current NPC (base ProbabilityWeighting times any
    /// matching ProbabilityWeightModifier factors). Supplied by the caller, which has the NPC/attribute context; this is
    /// the SAME weight the per-position walk uses, so the modifier is applied consistently at the seed stage.</param>
    public void ChooseSeedSubgroup(IEnumerable<FlattenedSubgroup> availableSeeds, Func<FlattenedAssetPack, double> packWeightSelector, Func<FlattenedSubgroup, double> seedWeightSelector)
    {
        // 1. Collect all unique ParentAssetPack members from availableSeeds.
        var uniqueAssetPacks = availableSeeds
            .Select(seed => seed.ParentAssetPack)
            .Distinct();

        // 2. Select a parent asset pack weighted by the caller-supplied selector (DistributionRules weight times any
        //    matching config-level modifier factor), so a config-level modifier biases the seed-pack choice.
        ChosenAssetPack = ProbabilityWeighting.SelectByProbability(uniqueAssetPacks, packWeightSelector);
        if (ChosenAssetPack == null)
        {
            return;
        }

        // 3. Filter availableSeeds to those whose ParentAssetPack equals the chosen one.
        var seedsFromChosenPack = availableSeeds
            .Where(seed => seed.ParentAssetPack == ChosenAssetPack);

        // 4. Select a seed weighted by the caller-supplied selector (base weight times modifier factor), so a
        //    modifier-boosted subgroup is preferred as the seed exactly as it would be at a walked position.
        ChosenSeed = ProbabilityWeighting.SelectByProbability(seedsFromChosenPack, seedWeightSelector);
    }
    
    /// <summary>
    /// Reverts the iteration to an earlier subgroup index when the current path can't be completed, optionally
    /// removing the offending subgroup from the reverted state so it won't be retried. Mutates
    /// <paramref name="iterationInfo"/>'s <see cref="ChosenAssetPack"/>.
    /// </summary>
    /// <param name="iterationInfo">The iteration state to roll back.</param>
    /// <param name="toRemove">Subgroup to remove from the reverted asset pack at the target index, or null to remove nothing.</param>
    /// <param name="currentIndex">The subgroup index currently being processed.</param>
    /// <param name="steps">How many indices to step back.</param>
    /// <returns>The index the caller's for-loop should resume from (one less than the revert target, since the loop re-increments).</returns>
    public static int BackTrack(AssignmentIteration iterationInfo, FlattenedSubgroup toRemove, int currentIndex, int steps)
    {
        FlattenedAssetPack revertTo = iterationInfo.BacktrackSnapshotsByPosition[currentIndex - steps];

        if (toRemove != null)
        {
            revertTo.Subgroups[currentIndex - steps].Remove(toRemove);
        }
        iterationInfo.ChosenAssetPack = revertTo;

        return currentIndex - steps - 1; // -1 because the calling for loop will then immediately add 1 back at the next iteration
    }
}