using Mutagen.Bethesda.Plugins;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace SynthEBD;

public class NPC2ProfileParser
{
    public Dictionary<FormKey, ModKey> AppearanceDictionary { get; set; } = new();

    public void Reinitialize(string filepath)
    {
        AppearanceDictionary.Clear();
        
        if (string.IsNullOrWhiteSpace(filepath) || !System.IO.File.Exists(filepath))
        {
            return;
        }

        try
        {
            var jsonContent = System.IO.File.ReadAllText(filepath);
            var tokenData = JsonSerializer.Deserialize<NPC2TokenFile>(jsonContent, new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true
            });

            if (tokenData?.ProcessedNpcs == null)
            {
                return;
            }

            foreach (var entry in tokenData.ProcessedNpcs)
            {
                // Key format is "FormID:PluginName" e.g. "002910:3DNPC.esp"
                var formKey = ConvertNPC2KeyToFormKey(entry.Key);
                if (formKey != null && !string.IsNullOrWhiteSpace(entry.Value.AppearancePlugin))
                {
                    var appearanceModKey = ModKey.FromNameAndExtension(entry.Value.AppearancePlugin);
                    if (!AppearanceDictionary.ContainsKey(formKey.Value))
                    {
                        AppearanceDictionary.Add(formKey.Value, appearanceModKey);
                    }
                }
            }
        }
        catch (Exception)
        {
            // Silently fail - dictionary will remain empty
            AppearanceDictionary.Clear();
        }
    }

    private FormKey? ConvertNPC2KeyToFormKey(string npc2Key)
    {
        // NPC2 format: "FormID:PluginName" e.g. "002910:3DNPC.esp"
        // FormKey format: "FormID:PluginName" e.g. "002910:3DNPC.esp"
        // These are actually the same format, so we can use TryFactory directly
        
        if (string.IsNullOrWhiteSpace(npc2Key))
        {
            return null;
        }

        return FormKey.TryFactory(npc2Key);
    }

    public bool GetNPCMod(FormKey npcFormKey, out ModKey? appearanceModKey)
    {
        if (AppearanceDictionary.ContainsKey(npcFormKey))
        {
            appearanceModKey = AppearanceDictionary[npcFormKey];
            return true;
        }
        else
        {
            appearanceModKey = null;
            return false;
        }
    }
}

/// <summary>
/// Represents the structure of the NPC_Token.json file generated by NPC Plugin Chooser 2
/// </summary>
public class NPC2TokenFile
{
    [JsonPropertyName("CreationDate")]
    public DateTime CreationDate { get; set; }

    [JsonPropertyName("ProcessedNpcs")]
    public Dictionary<string, NPC2ProcessedNpcEntry> ProcessedNpcs { get; set; } = new();
}

/// <summary>
/// Represents an individual NPC entry in the NPC_Token.json file
/// </summary>
public class NPC2ProcessedNpcEntry
{
    [JsonPropertyName("ModName")]
    public string ModName { get; set; } = string.Empty;

    [JsonPropertyName("AppearancePlugin")]
    public string AppearancePlugin { get; set; } = string.Empty;
}