using Mutagen.Bethesda.Plugins;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace SynthEBD;

/// <summary>
/// Parses the NPC_Token.json file produced by NPC Plugin Chooser 2 into maps of NPC FormKey to the chosen
/// appearance plugin and to the NPC2 output/merge plugin, used to restrict patching to NPC2-selected sources.
/// </summary>
public class NPC2ProfileParser
{
    /// <summary>NPC FormKey to the NPC2-selected appearance plugin, populated by <see cref="Reinitialize"/>.</summary>
    public Dictionary<FormKey, ModKey> AppearanceDictionary { get; set; } = new();
    /// <summary>NPC FormKey to the NPC2 output/merge plugin the appearance was written into, populated by <see cref="Reinitialize"/>.</summary>
    public Dictionary<FormKey, ModKey> MergeDictionary { get; set; } = new();

    /// <summary>
    /// Clears and repopulates <see cref="AppearanceDictionary"/> and <see cref="MergeDictionary"/> from the NPC2 token
    /// JSON at <paramref name="filepath"/>. No-ops if the path is empty or missing. On any parse error both dictionaries
    /// are left empty (the failure is swallowed).
    /// </summary>
    public void Reinitialize(string filepath)
    {
        AppearanceDictionary.Clear();
        MergeDictionary.Clear();
        
        if (string.IsNullOrWhiteSpace(filepath) || !System.IO.File.Exists(filepath))
        {
            return;
        }

        try
        {
            var jsonContent = System.IO.File.ReadAllText(filepath);
            var tokenData = JsonSerializer.Deserialize<NPC2TokenFile>(jsonContent, new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true
            });

            if (tokenData?.ProcessedNpcs == null)
            {
                return;
            }

            foreach (var entry in tokenData.ProcessedNpcs)
            {
                // Key format is "FormID:PluginName" e.g. "002910:3DNPC.esp"
                var formKey = ConvertNPC2KeyToFormKey(entry.Key);
                if (formKey != null && !string.IsNullOrWhiteSpace(entry.Value.AppearancePlugin))
                {
                    var appearanceModKey = ModKey.FromNameAndExtension(entry.Value.AppearancePlugin);
                    if (!AppearanceDictionary.ContainsKey(formKey.Value))
                    {
                        AppearanceDictionary.Add(formKey.Value, appearanceModKey);
                    }
                }
                
                if (formKey != null && !string.IsNullOrWhiteSpace(entry.Value.OutputPlugin))
                {
                    var outputModKey = ModKey.FromNameAndExtension(entry.Value.OutputPlugin);
                    if (!MergeDictionary.ContainsKey(formKey.Value))
                    {
                        MergeDictionary.Add(formKey.Value, outputModKey);
                    }
                }
            }
        }
        catch (Exception)
        {
            // Silently fail - dictionary will remain empty
            AppearanceDictionary.Clear();
        }
    }

    /// <summary>
    /// Converts an NPC2 token key (already in "FormID:PluginName" form) to a <see cref="FormKey"/>.
    /// Returns null for empty input or when the key is not a valid FormKey.
    /// </summary>
    private FormKey? ConvertNPC2KeyToFormKey(string npc2Key)
    {
        // NPC2 format: "FormID:PluginName" e.g. "002910:3DNPC.esp"
        // FormKey format: "FormID:PluginName" e.g. "002910:3DNPC.esp"
        // These are actually the same format, so we can use TryFactory directly
        
        if (string.IsNullOrWhiteSpace(npc2Key))
        {
            return null;
        }

        return FormKey.TryFactory(npc2Key);
    }

    /// <summary>
    /// Looks up the NPC2 appearance source plugin for <paramref name="npcFormKey"/>. Returns true and sets
    /// <paramref name="appearanceModKey"/> when present; otherwise returns false with a null out value.
    /// </summary>
    public bool GetNPCSourcePlugin(FormKey npcFormKey, out ModKey? appearanceModKey)
    {
        if (AppearanceDictionary.ContainsKey(npcFormKey))
        {
            appearanceModKey = AppearanceDictionary[npcFormKey];
            return true;
        }
        else
        {
            appearanceModKey = null;
            return false;
        }
    }
    
    /// <summary>
    /// Looks up the NPC2 output/merge plugin for <paramref name="npcFormKey"/>. Returns true and sets
    /// <paramref name="mergeModKey"/> when present; otherwise returns false with a null out value.
    /// </summary>
    public bool GetNPCMergePlugin(FormKey npcFormKey, out ModKey? mergeModKey)
    {
        if (MergeDictionary.ContainsKey(npcFormKey))
        {
            mergeModKey = MergeDictionary[npcFormKey];
            return true;
        }
        else
        {
            mergeModKey = null;
            return false;
        }
    }
}

/// <summary>
/// Represents the structure of the NPC_Token.json file generated by NPC Plugin Chooser 2
/// </summary>
public class NPC2TokenFile
{
    [JsonPropertyName("CreationDate")]
    public DateTime CreationDate { get; set; }

    [JsonPropertyName("ProcessedNpcs")]
    public Dictionary<string, NPC2ProcessedNpcEntry> ProcessedNpcs { get; set; } = new();
}

/// <summary>
/// Represents an individual NPC entry in the NPC_Token.json file
/// </summary>
public class NPC2ProcessedNpcEntry
{
    [JsonPropertyName("ModName")]
    public string ModName { get; set; } = string.Empty;

    [JsonPropertyName("AppearancePlugin")]
    public string AppearancePlugin { get; set; } = string.Empty;
    
    [JsonPropertyName("OutputPlugin")]
    public string OutputPlugin { get; set; } = string.Empty;
}